<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="2" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="TestNG Suite" duration-ms="232" started-at="2019-02-02T08:21:23Z" finished-at="2019-02-02T08:21:24Z">
    <groups>
      <group name="bvt">
        <method signature="TestCase2.validateTitles()[pri:0, instance:testnglearning.functional.TestCase2@192b07fd]" name="validateTitles" class="testnglearning.functional.TestCase2"/>
      </group> <!-- bvt -->
      <group name="functional">
        <method signature="TestCase1.doLogin()[pri:2, instance:testnglearning.functional.TestCase1@59ec2012]" name="doLogin" class="testnglearning.functional.TestCase1"/>
        <method signature="TestCase1.doUserReg()[pri:1, instance:testnglearning.functional.TestCase1@59ec2012]" name="doUserReg" class="testnglearning.functional.TestCase1"/>
        <method signature="TestCase3.doUserReg()[pri:1, instance:testnglearning.functional.TestCase3@1e127982]" name="doUserReg" class="testnglearning.functional.TestCase3"/>
      </group> <!-- functional -->
    </groups>
    <test name="Login Test" duration-ms="71" started-at="2019-02-02T08:21:23Z" finished-at="2019-02-02T08:21:24Z">
      <class name="testnglearning.functional.TestCase1">
        <test-method status="PASS" signature="createDBConnection()[pri:0, instance:testnglearning.functional.TestCase1@59ec2012]" name="createDBConnection" is-config="true" duration-ms="14" started-at="2019-02-02T08:21:23Z" finished-at="2019-02-02T08:21:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDBConnection -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testnglearning.functional.TestCase1@59ec2012]" name="launchBrowser" is-config="true" duration-ms="1" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="doUserReg()[pri:1, instance:testnglearning.functional.TestCase1@59ec2012]" name="doUserReg" duration-ms="9" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User reg test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User reg test failed
at org.testng.Assert.fail(Assert.java:96)
at testnglearning.functional.TestCase1.doUserReg(TestCase1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testnglearning.functional.TestCase1@59ec2012]" name="closeBrowser" is-config="true" duration-ms="2" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testnglearning.functional.TestCase1@59ec2012]" name="launchBrowser" is-config="true" duration-ms="1" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="doLogin()[pri:2, instance:testnglearning.functional.TestCase1@59ec2012]" name="doLogin" duration-ms="3" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login test failed
at org.testng.Assert.fail(Assert.java:96)
at testnglearning.functional.TestCase1.doLogin(TestCase1.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testnglearning.functional.TestCase1@59ec2012]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="closeDBConn()[pri:0, instance:testnglearning.functional.TestCase1@59ec2012]" name="closeDBConn" is-config="true" duration-ms="0" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBConn -->
      </class> <!-- testnglearning.functional.TestCase1 -->
    </test> <!-- Login Test -->
    <test name="Validate Title Test" duration-ms="34" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
      <class name="testnglearning.functional.TestCase2">
        <test-method status="FAIL" signature="validateTitles()[pri:0, instance:testnglearning.functional.TestCase2@192b07fd]" name="validateTitles" duration-ms="3" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Button not found expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Button not found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at testnglearning.functional.TestCase2.validateTitles(TestCase2.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- testnglearning.functional.TestCase2 -->
    </test> <!-- Validate Title Test -->
    <test name="Dependency Test" duration-ms="15" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
      <class name="testnglearning.functional.TestCase3">
        <test-method status="FAIL" signature="doUserReg()[pri:1, instance:testnglearning.functional.TestCase3@1e127982]" name="doUserReg" duration-ms="10" started-at="2019-02-02T08:21:24Z" finished-at="2019-02-02T08:21:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User not registered successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User not registered successfully
at org.testng.Assert.fail(Assert.java:96)
at testnglearning.functional.TestCase3.doUserReg(TestCase3.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
      </class> <!-- testnglearning.functional.TestCase3 -->
    </test> <!-- Dependency Test -->
  </suite> <!-- TestNG Suite -->
</testng-results>
